all:
	$(MAKE) -f Makefile.gui
	$(MAKE) -f Makefile.client

client:
	$(MAKE) -f Makefile.client

gui:
	$(MAKE) -f Makefile.gui

clean: 
	$(MAKE) -f Makefile.gui clean
	$(MAKE) -f Makefile.client clean

